[[CURRENCIES]]
code="AIWAY"
issuer="GBYNA57Q5KXQ6Q3JG35FTLXRGEPYUONM7TYV6TXFJRRWZPDUDHNQSY27"
name="AiWay"
desc="AiWay is an all-in-one AI platform for chatting, image generation, and accessing powerful language models through a simple interface."
image="https://raw.githubusercontent.com/medomohamed22/Tokens/main/AiWay.jpg"
